### ISSUE TITLE
[Bug] Wrong nummeric sorting of study trials

### ISSUE THREAD

**Issue by t-moe** [optuna/optuna-dashboard#20]
![2021-01-15-101022_1227x449_scrot](https://user-images.githubusercontent.com/11081135/104705363-1a7b8180-571a-11eb-85c4-7b55d72198d5.png)

# Bug report

When I sort the study trials by value, the values are sorted as string, instead of as number

## Expected Behavior

Correct numeric sorting

## Current Behavior and Steps to Reproduce

Create a study with a bunch of trials, where the trials have values with different number of digits. Then sort by value to obtain a view like in the screenshot above

## Context

optuna-dashboard installed via pip

**Comment by c-bata** [comment]
@t-moe I fixed this bug at #35 and released v0.2.3. Thank you for reporting!
https://github.com/optuna/optuna-dashboard/releases/tag/v0.2.3

**Comment by humatic** [comment]
I'm seeing this in `optuna-dashboard==0.16.2`

![Screenshot from 2024-10-22 18-02-09](https://github.com/user-attachments/assets/c7956590-716d-4a44-b62b-bb764e2a2548)

**Comment by robin-janssen** [comment]
Can confirm that this problem still exists in `optuna-dashboard==0.17.0`:

<img width="549" alt="Image" src="https://github.com/user-attachments/assets/3628a928-2cae-49a3-8ac4-bd2b7d16e04f" />
